#!/bin/bash
# ============================================================
# deploy.sh — Деплой Mary Belle на VPS Jino
# ============================================================
# Использование:
#   ./deploy/deploy.sh site    — деплой только сайта
#   ./deploy/deploy.sh cms     — деплой только Strapi CMS
#   ./deploy/deploy.sh all     — деплой всего
#   ./deploy/deploy.sh setup   — первичная настройка VPS
#   ./deploy/deploy.sh health  — проверка состояния VPS
# ============================================================

set -euo pipefail

# ── Загрузка секретов из .env ─────────────────────────────
DEPLOY_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${DEPLOY_DIR}/.env"

if [ -f "$ENV_FILE" ]; then
    set -a
    source "$ENV_FILE"
    set +a
    echo -e "\033[0;34m[DEPLOY]\033[0m Секреты загружены из deploy/.env"
else
    echo -e "\033[0;31m[ FAIL ]\033[0m Файл deploy/.env не найден!"
    echo "  Скопируй deploy/.env.example → deploy/.env и заполни секреты"
    exit 1
fi

# ── Настройки (из .env или дефолты) ───────────────────────
VPS_HOST="${VPS_HOST:?Задай VPS_HOST в deploy/.env}"
VPS_PORT="${VPS_PORT:?Задай VPS_PORT в deploy/.env}"
VPS_USER="${VPS_USER:-root}"
SSH_KEY="${SSH_KEY_PATH:-$HOME/.ssh/id_ed25519}"

SITE_LOCAL="$(cd "$DEPLOY_DIR/.." && pwd)"
CMS_LOCAL="$(cd "$DEPLOY_DIR/../../mary-belle-cms2" && pwd 2>/dev/null || echo "")"

SITE_REMOTE="${SITE_REMOTE:-/opt/mary-belle}"
CMS_REMOTE="${CMS_REMOTE:-/opt/mary-belle-cms}"

SSH_CMD="ssh -i $SSH_KEY -p $VPS_PORT -o StrictHostKeyChecking=accept-new $VPS_USER@$VPS_HOST"
SCP_CMD="scp -i $SSH_KEY -P $VPS_PORT"

# ── Цвета ──────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log()   { echo -e "${BLUE}[DEPLOY]${NC} $1"; }
ok()    { echo -e "${GREEN}[  OK  ]${NC} $1"; }
warn()  { echo -e "${YELLOW}[ WARN ]${NC} $1"; }
fail()  { echo -e "${RED}[ FAIL ]${NC} $1"; exit 1; }

# ── Проверка SSH ───────────────────────────────────────────
check_ssh() {
    log "Проверяю SSH-подключение к VPS..."
    if ! $SSH_CMD "echo ok" &>/dev/null; then
        fail "Не удалось подключиться к VPS. Проверь SSH-ключ и доступность сервера."
    fi
    ok "SSH-подключение работает"
}

# ── Предеплой тесты ───────────────────────────────────────
run_tests() {
    log "Запускаю предеплой тесты..."
    if [ -f "$SITE_LOCAL/deploy/test.sh" ]; then
        bash "$SITE_LOCAL/deploy/test.sh"
    else
        warn "Файл test.sh не найден, пропускаю тесты"
    fi
}

# ── Бэкап на VPS ──────────────────────────────────────────
backup_remote() {
    local name=$1
    local path=$2
    log "Создаю бэкап $name на VPS..."
    $SSH_CMD "
        BACKUP_DIR=/opt/backups/\$(date +%Y%m%d_%H%M%S)_${name}
        mkdir -p \$BACKUP_DIR
        if [ -d $path ]; then
            cp -r $path/package.json \$BACKUP_DIR/ 2>/dev/null || true
            cp -r $path/.env* \$BACKUP_DIR/ 2>/dev/null || true
            # Бэкап БД (SQLite)
            find $path -name '*.db' -exec cp {} \$BACKUP_DIR/ \; 2>/dev/null || true
        fi
        # Удаляем бэкапы старше 7 дней
        find /opt/backups -maxdepth 1 -type d -mtime +7 -exec rm -rf {} \; 2>/dev/null || true
        echo \$BACKUP_DIR
    "
    ok "Бэкап $name создан"
}

# ── Генерация .env.local для VPS ─────────────────────────
generate_env_local() {
    local output_file="$1"
    cat > "$output_file" <<EOF
# Auto-generated by deploy.sh — $(date +%Y-%m-%d\ %H:%M)
# НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ — будет перезаписан при следующем деплое
METRIKA_OAUTH_TOKEN=${METRIKA_OAUTH_TOKEN}
AMO_SUBDOMAIN=${AMO_SUBDOMAIN}
AMO_TOKEN=${AMO_TOKEN}
AMO_WEBHOOK_SECRET=${AMO_WEBHOOK_SECRET:-}
MB_TG_BOT_TOKEN=${MB_TG_BOT_TOKEN}
MB_TG_CHAT_ID=${MB_TG_CHAT_ID}
EMAIL_TO=${EMAIL_TO}
SMTP_USER=${SMTP_USER}
SMTP_PASS=${SMTP_PASS}
PAYLOAD_SECRET=${PAYLOAD_SECRET}
STRAPI_URL=${STRAPI_URL}
STRAPI_TOKEN=${STRAPI_TOKEN}
EOF
}

# ── Деплой сайта ──────────────────────────────────────────
deploy_site() {
    log "═══ Деплой сайта Next.js ═══"

    cd "$SITE_LOCAL"

    # ─ Проверка версии Node ─
    if [ -f ".nvmrc" ]; then
        EXPECTED_NODE=$(cat .nvmrc | tr -d '[:space:]')
        CURRENT_NODE=$(node -v | sed 's/v\([0-9]*\).*/\1/')
        if [ "$CURRENT_NODE" != "$EXPECTED_NODE" ]; then
            fail "Node.js v${CURRENT_NODE}, нужен v${EXPECTED_NODE} (см. .nvmrc). Запусти: nvm use"
        fi
        ok "Node.js v${CURRENT_NODE} совпадает с .nvmrc"
    fi

    # ─ Сборка (если .next уже есть после test.sh — пропускаем) ─
    if [ ! -f ".next/BUILD_ID" ]; then
        log "Сборка проекта..."
        npm run build || fail "Сборка Next.js провалилась!"
        ok "Сборка успешна"
    else
        ok "Сборка уже готова (BUILD_ID: $(cat .next/BUILD_ID))"
    fi

    # ─ Архив ─
    # ВАЖНО: исключаем .env.local (локальный, с localhost), deploy/.env (секреты)
    # Включаем deploy/ecosystem.config.js (нужен PM2 на VPS)
    log "Создаю архив..."
    tar czf /tmp/mary-belle-site.tar.gz \
        --exclude='node_modules' \
        --exclude='.next/cache' \
        --exclude='.git' \
        --exclude='.env.local' \
        --exclude='.env*.local' \
        --exclude='deploy/.env' \
        --exclude='payload.db' \
        --exclude='payload.db-journal' \
        --exclude='*.mp4' \
        --exclude='*.webm' \
        -C "$SITE_LOCAL" .
    ok "Архив создан: $(du -h /tmp/mary-belle-site.tar.gz | cut -f1)"

    # ─ Бэкап на VPS ─
    backup_remote "site" "$SITE_REMOTE"

    # ─ Загрузка архива ─
    log "Загружаю на VPS..."
    $SCP_CMD /tmp/mary-belle-site.tar.gz "$VPS_USER@$VPS_HOST:/tmp/"
    ok "Архив загружен"

    # ─ Распаковка и установка зависимостей ─
    # ПОРЯДОК: 1) tar extract  2) .env.local  3) npm install  4) pm2 restart
    log "Разворачиваю на VPS..."
    $SSH_CMD "
        set -e
        mkdir -p $SITE_REMOTE
        cd $SITE_REMOTE

        # 1. Распаковываем код (без .env.local — он исключён из архива)
        tar xzf /tmp/mary-belle-site.tar.gz
        rm -f /tmp/mary-belle-site.tar.gz

        # 2. Установка зависимостей
        npm install --production

        echo 'Code extracted and deps installed'
    "
    ok "Код развёрнут"

    # ─ Загрузка production .env.local (ПОСЛЕ tar extract, чтобы не перезатёрся) ─
    log "Загружаю production .env.local..."
    ENV_REMOTE_FILE="/tmp/.env.local.deploy"
    generate_env_local "$ENV_REMOTE_FILE"
    $SCP_CMD "$ENV_REMOTE_FILE" "$VPS_USER@$VPS_HOST:$SITE_REMOTE/.env.local"
    rm -f "$ENV_REMOTE_FILE"
    ok "Production .env.local загружен на VPS"

    # ─ Перезапуск и health check ─
    log "Перезапускаю сайт..."
    $SSH_CMD "
        set -e
        cd $SITE_REMOTE

        # Перезапуск (ecosystem.config.js теперь есть в deploy/)
        pm2 restart mary-belle-site 2>/dev/null || pm2 start deploy/ecosystem.config.js --only mary-belle-site

        # Health check — ждём до 15с
        echo 'Waiting for site to start...'
        for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15; do
            if curl -sf http://127.0.0.1:3000 > /dev/null 2>&1; then
                echo 'Site is UP'
                exit 0
            fi
            sleep 1
        done

        echo 'WARNING: Site may not be responding after 15s'
        pm2 logs mary-belle-site --lines 20 --nostream 2>/dev/null || true
    "
    ok "Сайт задеплоен"

    # Очистка локально
    rm -f /tmp/mary-belle-site.tar.gz
}

# ── Деплой CMS ────────────────────────────────────────────
deploy_cms() {
    log "═══ Деплой Strapi CMS ═══"

    if [ -z "$CMS_LOCAL" ] || [ ! -d "$CMS_LOCAL" ]; then
        fail "Папка CMS не найдена: mary-belle-cms2/"
    fi

    # Архив CMS (без node_modules, .cache, .env, БД)
    log "Создаю архив CMS..."
    tar czf /tmp/mary-belle-cms.tar.gz \
        --exclude='node_modules' \
        --exclude='dist' \
        --exclude='.cache' \
        --exclude='.tmp' \
        --exclude='.strapi' \
        --exclude='.env' \
        --exclude='.git' \
        -C "$CMS_LOCAL" .
    ok "Архив CMS создан: $(du -h /tmp/mary-belle-cms.tar.gz | cut -f1)"

    # Бэкап (включая SQLite БД)
    backup_remote "cms" "$CMS_REMOTE"

    # Загрузка
    log "Загружаю CMS на VPS..."
    $SCP_CMD /tmp/mary-belle-cms.tar.gz "$VPS_USER@$VPS_HOST:/tmp/"
    ok "Архив CMS загружен"

    # Загружаем ecosystem.config.js на VPS (для PM2)
    $SCP_CMD "$DEPLOY_DIR/ecosystem.config.js" "$VPS_USER@$VPS_HOST:$CMS_REMOTE/ecosystem.config.js"

    # Распаковка и запуск
    log "Разворачиваю CMS на VPS..."
    $SSH_CMD "
        set -e
        mkdir -p $CMS_REMOTE
        cd $CMS_REMOTE

        # Сохраняем .env и БД перед распаковкой
        [ -f .env ] && cp .env /tmp/.env.cms.bak
        for db in *.db; do
            [ -f \"\$db\" ] && cp \"\$db\" /tmp/ 2>/dev/null || true
        done

        pm2 stop strapi-cms 2>/dev/null || true

        # Распаковываем код
        tar xzf /tmp/mary-belle-cms.tar.gz

        # Возвращаем .env
        [ -f /tmp/.env.cms.bak ] && mv /tmp/.env.cms.bak .env

        # Возвращаем БД (если были)
        for db in /tmp/*.db; do
            [ -f \"\$db\" ] && mv \"\$db\" . 2>/dev/null || true
        done

        # Установка и сборка
        npm install --production
        npm run build

        # Перезапуск
        pm2 restart strapi-cms 2>/dev/null || pm2 start ecosystem.config.js --only strapi-cms

        # Health check — ждём до 20с (Strapi стартует медленнее)
        echo 'Waiting for Strapi to start...'
        for i in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20; do
            if curl -sf http://127.0.0.1:1337/_health > /dev/null 2>&1; then
                echo 'Strapi is UP'
                rm -f /tmp/mary-belle-cms.tar.gz
                exit 0
            fi
            sleep 1
        done

        echo 'WARNING: Strapi may not be responding after 20s'
        pm2 logs strapi-cms --lines 20 --nostream 2>/dev/null || true
        rm -f /tmp/mary-belle-cms.tar.gz
    "
    ok "Strapi CMS задеплоен"

    rm -f /tmp/mary-belle-cms.tar.gz
}

# ── Первичная настройка VPS ───────────────────────────────
setup_vps() {
    log "═══ Первичная настройка VPS ═══"
    check_ssh

    $SSH_CMD "
        set -e

        # Обновляем пакеты
        apt-get update && apt-get upgrade -y

        # Node.js 22 (если не установлен)
        if ! command -v node &>/dev/null; then
            curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
            apt-get install -y nodejs
        fi
        echo 'Node.js:' \$(node -v)

        # PM2
        if ! command -v pm2 &>/dev/null; then
            npm install -g pm2
            pm2 startup systemd -u root --hp /root
        fi
        echo 'PM2:' \$(pm2 -v)

        # Nginx
        if ! command -v nginx &>/dev/null; then
            apt-get install -y nginx
            systemctl enable nginx
        fi
        echo 'Nginx:' \$(nginx -v 2>&1)

        # Certbot
        if ! command -v certbot &>/dev/null; then
            apt-get install -y certbot python3-certbot-nginx
        fi

        # Директории
        mkdir -p /opt/mary-belle/deploy /opt/mary-belle-cms /opt/backups /var/log/pm2

        echo ''
        echo '=== VPS готов ==='
        echo 'Node:' \$(node -v)
        echo 'npm:' \$(npm -v)
        echo 'PM2:' \$(pm2 -v)
    "

    # Загружаем конфиги на VPS
    log "Загружаю конфиги..."
    $SCP_CMD "$DEPLOY_DIR/ecosystem.config.js" "$VPS_USER@$VPS_HOST:$SITE_REMOTE/deploy/ecosystem.config.js"
    $SCP_CMD "$DEPLOY_DIR/nginx/mary-belle.conf" "$VPS_USER@$VPS_HOST:/etc/nginx/conf.d/mary-belle.conf"
    $SCP_CMD "$DEPLOY_DIR/nginx/strapi.conf" "$VPS_USER@$VPS_HOST:/etc/nginx/conf.d/strapi.conf"

    $SSH_CMD "nginx -t && systemctl reload nginx"

    ok "VPS настроен, nginx конфиги загружены"
}

# ── Health check после деплоя ─────────────────────────────
health_check() {
    log "Проверяю health после деплоя..."

    $SSH_CMD "
        echo '--- PM2 Status ---'
        pm2 jlist 2>/dev/null | python3 -c \"
import sys, json
for p in json.load(sys.stdin):
    status = p.get('pm2_env', {}).get('status', '?')
    name = p.get('name', '?')
    mem = p.get('monit', {}).get('memory', 0) // 1024 // 1024
    print(f'  {name}: {status} ({mem}MB)')
\" 2>/dev/null || pm2 list

        echo ''
        echo '--- Site ---'
        curl -so /dev/null -w 'HTTP %{http_code} (%{time_total}s)' http://127.0.0.1:3000/ || echo 'OFFLINE'

        echo ''
        echo '--- Strapi ---'
        curl -so /dev/null -w 'HTTP %{http_code} (%{time_total}s)' http://127.0.0.1:1337/_health || echo 'OFFLINE'

        echo ''
        echo '--- .env.local проверка ---'
        if [ -f /opt/mary-belle/.env.local ]; then
            echo 'STRAPI_URL=' \$(grep '^STRAPI_URL=' /opt/mary-belle/.env.local | cut -d= -f2-)
            VARS=\$(grep -c '=' /opt/mary-belle/.env.local)
            echo \"Переменных: \$VARS\"
        else
            echo 'WARNING: .env.local не найден!'
        fi

        echo ''
        echo '--- Node.js ---'
        echo \"Node: \$(node -v), npm: \$(npm -v)\"

        echo ''
        echo '--- Disk ---'
        df -h / | tail -1

        echo ''
        echo '--- RAM ---'
        free -h | grep Mem
    "
}

# ── Точка входа ───────────────────────────────────────────
ACTION="${1:-}"

case "$ACTION" in
    site)
        check_ssh
        run_tests
        deploy_site
        health_check
        ;;
    cms)
        check_ssh
        deploy_cms
        health_check
        ;;
    all)
        check_ssh
        run_tests
        deploy_site
        deploy_cms
        health_check
        ;;
    setup)
        setup_vps
        ;;
    health)
        check_ssh
        health_check
        ;;
    *)
        echo "Использование: $0 {site|cms|all|setup|health}"
        echo ""
        echo "  site   — деплой Next.js сайта"
        echo "  cms    — деплой Strapi CMS"
        echo "  all    — деплой всего (сайт + CMS)"
        echo "  setup  — первичная настройка VPS"
        echo "  health — проверка состояния VPS"
        exit 1
        ;;
esac

echo ""
ok "Готово!"
